name = "www-html"
compatibility_date = "2026-03-08"

main = "@astrojs/cloudflare/entrypoints/server"

compatibility_flags = [
  "nodejs_compat",
  "global_fetch_strictly_public"
]

[assets]
binding = "ASSETS"
directory = "./dist/client"

[[kv_namespaces]]
binding = "SESSION"
id = "1b1f9788e82346bdb2219ed4712abf4a"
